### PR TITLE
fix bug in `@mlj_model` macro

### PR DESCRIPTION
**Pull request by OkonSamuel**

### CODE REVIEW

**Comment by OkonSamuel** [comment]
cc. @ablaom a review at your own time would be appreciated

**Comment by ablaom** [comment]
I'm supposing the problem has something to do with multiple type definitions?

If you can confirm that MLJModels passes tests with this change, I'm happy. Go ahead and merge when ready and please tag a new release yourself if this is urgent.

Thanks!

**Comment by OkonSamuel** [comment]
> I'm supposing the problem has something to do with multiple type definitions?

Yeah


> confirm that MLJModels passes tests with this change,

Yes. MLJModels tests pass.


> Go ahead and merge when ready and please tag a new release yourself if this is urgent.

@ablaom Happy to do that maybe later today but I don't have write access to this repo

**Comment by ablaom** [comment]
@OkonSamuel Invitation to maintain should be heading your way. Many thanks. There's no urgency on my side for this.

**Pull request merged**
