### PR TITLE
Export `scitype`

### PR DESCRIPTION
**Pull request by ablaom**
Addresses #129

### CODE REVIEW

**Comment by ablaom** [comment]
@OkonSamuel If you are happy with this please merge, make a PR onto master and tag a new release directly.

**Comment by OkonSamuel** [comment]
> @OkonSamuel If you are happy with this please merge, make a PR onto master and tag a new release directly.

@ablaom I guess the reason for not exporting the `scitype` function from `ScientificTypesBase` is because it's the two argument definition i.e `scitype(X, Convention)` whereas the single argument definition is now defined in `ScientificTypes.jl` and is distinct from the one in `ScientifictypesBase`. So I guess this is breaking. But I think I have a work around that can still allow us export this function but avoid being a breaking change.
```julia
scitype(X) = scitype(get_interface_mode(), X)
scitype(::LightInterface, X) = throw(ArgumentError("FullInterface is needed..."))
```
Then at **MLJBase** we define something like.
```julia
scitype(::FullInterface, X ) = ScientificTypes.scitype(X)
```

**Comment by ablaom** [comment]
@OkonSamuel Thanks for that. Thanks for the clarification. I see this is trickier than I realised.

You are saying that:

1. This PR, as is, will break MLJBase, yes?
2. If we add to this PR the code suggested above, then this PR will still break MLJBase, but the fix is not too bad, namely the second bit of code you suggest above, yes?
3. If both these changes are made, we will have successfully patched the inadvertent breaking behaviour introduced by MLJModelInterface 1.3.4 (failing to export a previously exported method) yes?

If all yes, this sounds like a good plan, so long as:

A. We have backwards compatibility: All MLJBase 0.18.* are compatible with the new MLJModelInteface 1.3.5. 
B. We yank MLJBase 0.19 and  0.19.1 (already released) from General, after the new patch MLJBase 0.19.2

**Comment by OkonSamuel** [comment]
> * This PR, as is, will break MLJBase, yes?
> * If we add to this PR the code suggested above, then this PR will still break MLJBase, but the fix is not too bad, namely the second bit of code you suggest above, yes?
> * If both these changes are made, we will have successfully patched the inadvertent breaking behaviour introduced by MLJModelInterface 1.3.4 (failing to export a previously exported method) yes?

@ablaom all yes.

**Comment by ablaom** [comment]
Closed in favour of #133

**Pull request closed without merging**
