### PR TITLE
`schema` interface

### PR DESCRIPTION
**Pull request by aviatesk**
I found we need this in order to enable for model providers to implement something discussed in https://github.com/alan-turing-institute/MLJLinearModels.jl/issues/60

### CODE REVIEW

**Comment by tlienart** [comment]
Oh good point, this would also need a PR to MLJBase#dev following the examples here: https://github.com/alan-turing-institute/MLJBase.jl/blob/dev/src/interface/data_utils.jl where `MLJScientificTypes.schema` is called: https://github.com/alan-turing-institute/MLJScientificTypes.jl/blob/dev/src/schema.jl

Would you mind opening a PR there as well? thanks a lot!!

**Comment by tlienart** [comment]
I think it should just be

```julia
MMI.schema(::FI, ::Val{:table}, X; kw...) = schema(X; kw...)
```

but would need to be tested to check there's no clash.

**Comment by aviatesk** [comment]
> Would you mind opening a PR there as well? thanks a lot!!

do you mean [this PR](https://github.com/alan-turing-institute/MLJBase.jl/pull/280) isn't enough ?

**Comment by aviatesk** [comment]
the point of having 
```julia
schema(::Mode, ::Val{:other}, X; kw...) = nothing

schema(::LightInterface, ::Val{:table}, X; kw...) = errlight("schema")
```

is that `X` can be just `Array` object and no schema is not implemented for that.

**Comment by aviatesk** [comment]
test added, could you review this or hear your idea, @ablaom ?

**Comment by tlienart** [comment]
> > Would you mind opening a PR there as well? thanks a lot!!
> 
> do you mean [this PR](https://github.com/alan-turing-institute/MLJBase.jl/pull/280) isn't enough ?

I apologise, I had not seen this. 

I'll merge both PRs into dev

**Comment by aviatesk** [comment]
no worries, thanks for your quick response, @tlienart ;)

**Pull request merged**
